### ISSUE TITLE
"Exit" on exit

### ISSUE THREAD

**Issue by GammaGames** [flathub/it.mijorus.smile#24]
The minimize on exit command is pretty nice:
![image](https://user-images.githubusercontent.com/7832163/225941227-a721d1bf-4022-4071-9851-163542ae4b64.png)

But I would prefer if the app exited completely after picking an emoji. Can that be an option?

**Comment by mijorus** [comment]
It already is.

If you uncheck "run in the background" and "minimize on exit", the application will quit on exit (the process itself will be terminated).

**Comment by GammaGames** [comment]
I am a fool 👍️ Thank you!
(emoji inserted with Smile)
